# https://leetcode.com/problems/find-the-difference/description/

'''

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

'''

s = input()
t = input()

s = set([x for x in s])
t = set([x for x in t])
print(list(t-s)[0])